source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!

target 'TFCoreFoundation' do
pod 'YYImage'
pod 'YYText'
pod 'TFPhotoBrowser', :git => 'https://github.com/TimeFaceCoder/TFPhotoBrowser.git'
pod 'TFCamera', :git => 'https://github.com/TimeFaceCoder/TFCamera.git'
pod 'MYTableViewManager', :git => 'https://github.com/TimeFaceCoder/MYTableViewManager.git'
pod 'AliyunOSSiOS', :git => 'https://github.com/aliyun/AliyunOSSiOS.git'
pod 'TFHotfix', :git => 'https://github.com/TimeFaceCoder/TFHotfix.git'
pod 'TFNetwork', :git => 'https://github.com/TimeFaceCoder/TFNetwork.git'
pod 'TFNavigator', :git => 'https://github.com/TimeFaceCoder/TFNavigator.git'
pod 'TFUploadAssistant', :git => 'https://github.com/TimeFaceCoder/TFUploadAssistant.git'
pod 'TFTableViewDataSource', :git => 'https://github.com/TimeFaceCoder/TFTableViewDataSource.git'
pod 'AsyncDisplayKit', :git => 'https://github.com/facebook/AsyncDisplayKit.git'
pod 'SVProgressHUD'
pod 'JDStatusBarNotification', :git => 'https://github.com/TimeFaceCoder/JDStatusBarNotification.git'
pod 'FLAnimatedImage'
pod 'WebViewJavascriptBridge'
pod 'NJKWebViewProgress'
pod 'JSONModel'
pod 'SSKeychain'
end
